# Generated by Django 4.0.4 on 2022-05-31 10:53

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(null=True, upload_to='images_uploaded')),
                ('image_2', models.ImageField(null=True, upload_to='images_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', versatileimagefield.fields.VersatileImageField(upload_to='images_1/testimagemodel_1/', verbose_name='Image_1')),
                ('Name', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.FileField(null=True, upload_to='videos_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/testimagemodel/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_video', models.FileField(null=True, upload_to='videos_uploaded')),
                ('banner_img', versatileimagefield.fields.VersatileImageField(upload_to='images/Banner/', verbose_name='Image')),
                ('ayurved_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('food_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('package_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('consulting_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('bistander_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('appartment_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('recommend1_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('recommend2_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('recommend3_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('helping_img', versatileimagefield.fields.VersatileImageField(upload_to='images/facility/', verbose_name='Image')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='momslap_app.testimonial')),
            ],
        ),
    ]
