# Generated by Django 4.0.4 on 2022-05-31 10:57

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('momslap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='appartment_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='ayurved_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='banner_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/Banner/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='bistander_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='consulting_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='food_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='helping_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='package_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='recommend1_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='recommend2_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='recommend3_img',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images/facility/'),
        ),
    ]
