# Generated by Django 4.0.4 on 2022-06-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momslap_app', '0002_alter_package_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
