# Generated by Django 4.0.4 on 2022-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momslap_app', '0003_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('Vip', 'vip'), ('Normal', 'normal')], max_length=200),
        ),
    ]
